-- MySQL Script generated by MySQL Workbench
-- qui 12 mar 2020 17:58:51 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema CRUD_MVC
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema CRUD_MVC
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `CRUD_MVC` DEFAULT CHARACTER SET utf8 ;
USE `CRUD_MVC` ;

-- -----------------------------------------------------
-- Table `CRUD_MVC`.`comentario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CRUD_MVC`.`comentario` (
  `id` INT(11) NOT NULL,
  `nome` VARCHAR(200) NULL,
  `mensagem` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `CRUD_MVC`.`postagem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CRUD_MVC`.`postagem` (
  `id` INT NOT NULL,
  `postagem` VARCHAR(200) NOT NULL,
  `conteudo` VARCHAR(45) NOT NULL,
  `comentario_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `comentario_id`),
  INDEX `fk_postagem_comentario_idx` (`comentario_id` ASC),
  CONSTRAINT `fk_postagem_comentario`
    FOREIGN KEY (`comentario_id`)
    REFERENCES `CRUD_MVC`.`comentario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
